import Head from "next/head";
import { useState } from "react";

import { SearchBar } from "../src/components/SearchBar";
import styles from "../styles/Home.module.scss";
import { ListItem } from "../src/components/ListItem";

export default function Home() {
  const [query, setQuery] = useState();
  const [items, setItems] = useState([]);
  console.log(items);

  const handleSearchClick = () => {
    fetch(`http://localhost:3000/api/items?q=${query}`)
      .then((response) => response.json())
      .then(({ data }) => setItems(data.results));
  };

  const handleChange = (element) => {
    setQuery(element.target.value);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Meli App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <SearchBar
          handleSearchClick={handleSearchClick}
          handleChange={handleChange}
        />
        <div className={styles.search__items}>
          {items.map((el) => (
            <ListItem
              key={el.id}
              title={el.title}
              image={el.thumbnail}
              price={el.price}
              location={el.address.state_name}
              shipping={el.shipping.free_shipping}
            />
          ))}
        </div>
      </main>
    </div>
  );
}
