import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import searchIcon from "../assets/img/ic_Search.png";
import logoMeli from "../assets/img/Logo_ML.png";
import { Input, Button } from "reactstrap";
import { useState } from "react";

export default function Home() {
  const [query, setQuery] = useState();
  const [items, setItems] = useState([]);
  console.log(items);

  const handleSearchClick = () => {
    fetch(`http://localhost:3000/api/items?q=${query}`)
      .then((response) => response.json())
      .then(({ data }) => console.log(data.results));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Meli App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.nav__container}>
          <div className={styles.nav__logo}>
            <Image src={logoMeli} alt="LOGO" />
          </div>

          <Input
            className={styles.search}
            name="search"
            placeholder="Nunca dejes de buscar"
            onChange={(element) => setQuery(element.target.value)}
          />
          <Button onClick={handleSearchClick} className={styles.btn__search}>
            <Image src={searchIcon} alt="SEARCH_ICON" />
          </Button>
        </div>
      </main>
    </div>
  );
}
